# Generated by Django 5.2.5 on 2025-08-11 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('especie', models.CharField(default='animal', max_length=30)),
                ('raza', models.CharField(max_length=30)),
                ('edad', models.IntegerField()),
                ('estado', models.CharField(choices=[('ON', 'Dentro la veterinaria'), ('OFF', 'Fuera de la veterinaria')], default='OFF', max_length=3)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.person')),
            ],
        ),
    ]
