# Generated by Django 5.2.5 on 2025-08-15 16:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='edad',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='estado',
            field=models.CharField(choices=[('ON', 'Admision veterinaria | guarderia'), ('OFF', 'En casa')], default='OFF', max_length=3),
        ),
    ]
